### ISSUE TITLE
Scoped packages

### ISSUE THREAD

**Issue by jimafisk** [livebud/npm#1]
NPM allows for [scoped / namespaced package](https://stackoverflow.com/questions/36667258/what-is-the-meaning-of-the-at-prefix-on-npm-packages) for example you might have a `package.json` like:

```json
"dependencies": {                
  "@stripe/stripe-js": "^2.1.11",
}
```

The download URL for this looks like: https://registry.npmjs.org/@stripe/stripe-js/-/stripe-js-2.1.11.tgz

Using a scoped package creates issues because this project is splitting the package name from the version number using the `@` character: https://github.com/livebud/npm/blob/main/npm.go#L80

And the URL formatter (https://github.com/livebud/npm/blob/main/npm.go#L110) would need allow another replacement:
```go
fmt.Sprintf(`https://registry.npmjs.org/%[1]s%[2]s/-/%[2]s-%[3]s.tgz`, p.Scope, p.Name, p.Version)
```
Where:
- Scope = `@stripe/` (optionally `""` for non-scoped packages)
- Name = `stripe-js`
- Version = `2.1.11`

**Comment by matthewmueller** [comment]
Good call! Just added support for scoped modules in v0.0.2

**Comment by jimafisk** [comment]
Wow that was fast :open_mouth: :tada: 

Works great, thanks @matthewmueller!
